import { ArticleType } from "common";
import { Article } from "./schema.js";

// !!! TypeScript !!!
// Omit<> - don't need _id field in createArticle, it will be generated by MongoDB
async function createArticle(article: Omit<ArticleType, "_id">) {
  const dbArticle = new Article(article);
  await dbArticle.save();
  return dbArticle;
}

async function retrieveArticleList() {
  return await Article.find();
}

async function retrieveArticle(id: string) {
  return await Article.findById(id);
}

async function updateArticle(article: ArticleType) {
  const dbArticle = await Article.findOneAndUpdate({ _id: article._id }, article);
  return dbArticle !== undefined;
}

async function deleteArticle(id: string) {
  await Article.deleteOne({ _id: id });
}

export { createArticle, retrieveArticle, retrieveArticleList, updateArticle, deleteArticle };
