import { zodSchema } from "@zodyac/zod-mongoose";
import { ArticleSchema } from "common";
import mongoose from "mongoose";

// !!! TypeScript !!!
// The zodSchema function is used to create a Mongoose schema from a Zod schema.
// We omit the _id field because it will be generated by MongoDB.
const articleSchema = zodSchema(ArticleSchema.omit({ _id: true }), {
  timestamps: {}
});

const Article = mongoose.model("Article", articleSchema);

export { Article };
